from fastapi import APIRouter, HTTPException
from typing import List, Dict, Any

router = APIRouter()

REGISTRY_SOURCES = [
    {
        "id": "src-unctad",
        "source_name": "UNCTAD Data Hub",
        "provider": "United Nations Conference on Trade and Development",
        "base_url": "https://unctadstat.unctad.org/EN/",
        "documentation_url": "https://unctadstat.unctad.org/EN/",
        "dataset_name": "Maritime Transport Indicators & Liner Shipping Connectivity Index (LSCI)",
        "access_type": "public",
        "license_notes": "Public United Nations statistical open data repository",
        "update_frequency": "Quarterly & Annual",
        "historical_coverage": "2004 - Present",
        "fields": ["liner_connectivity_index", "merchant_fleet_dwt", "container_port_throughput_teu", "seaborne_trade_volume"],
        "auth_required": False,
        "active": True,
        "last_success_at": "2 hours ago",
        "last_error": None,
        "rate_limit_notes": "Open access; cached bulk queries recommended",
    },
    {
        "id": "src-un-comtrade",
        "source_name": "UN Comtrade API",
        "provider": "United Nations Statistics Division",
        "base_url": "https://comtradeapi.un.org/public/v1",
        "documentation_url": "https://uncomtrade.org/docs/un-comtrade-api/",
        "dataset_name": "International Merchandise Trade Statistics (Bilateral Flows)",
        "access_type": "api",
        "license_notes": "Open standard tier with API key for extended rate limits; Developer portal: https://comtrade.developer.un.org/",
        "update_frequency": "Monthly",
        "historical_coverage": "2010 - Present",
        "fields": ["trade_value_usd", "net_weight_kg", "partner_code", "reporter_code", "commodity_code_hs"],
        "auth_required": True,
        "active": False,
        "last_success_at": None,
        "last_error": "API Key Required (COMTRADE_API_KEY)",
        "rate_limit_notes": "Rate limit: 500 requests per day for standard tier",
    },
    {
        "id": "src-noaa-ncei",
        "source_name": "NOAA NCEI Data Service",
        "provider": "National Centers for Environmental Information (NOAA)",
        "base_url": "https://www.ncei.noaa.gov/support/access-data-service-api-user-documentation",
        "documentation_url": "https://www.ncei.noaa.gov/support/access-data-service-api-user-documentation",
        "dataset_name": "Access Data Service API & Global Marine Surface Weather Observations",
        "access_type": "public",
        "license_notes": "Public domain US federal meteorological observations",
        "update_frequency": "Daily",
        "historical_coverage": "1970 - Present",
        "fields": ["wind_speed", "wind_direction", "sea_level_pressure", "air_temperature", "precipitation"],
        "auth_required": False,
        "active": True,
        "last_success_at": "1 hour ago",
        "last_error": None,
        "rate_limit_notes": "Public access with rate throttling",
    },
    {
        "id": "src-noaa-cdo",
        "source_name": "NOAA Climate Data Online (CDO)",
        "provider": "NOAA NCEI",
        "base_url": "https://www.ncei.noaa.gov/cdo-web/api/v2",
        "documentation_url": "https://www.ncei.noaa.gov/cdo-web/webservices/v2",
        "dataset_name": "Climate Data Online Web Services v2",
        "access_type": "api",
        "license_notes": "Public domain; requires free personal web service token",
        "update_frequency": "Daily / Hourly",
        "historical_coverage": "1970 - Present",
        "fields": ["tavg", "prcp", "awnd", "wdf2", "wdf5"],
        "auth_required": True,
        "active": False,
        "last_success_at": None,
        "last_error": "API Key Required (NOAA_API_TOKEN)",
        "rate_limit_notes": "Rate limit: 5 requests per second, 10,000 requests per day",
    },
    {
        "id": "src-noaa-erddap",
        "source_name": "NOAA CoastWatch ERDDAP",
        "provider": "NOAA National Marine Fisheries Service & OceanWatch",
        "base_url": "https://coastwatch.pfeg.noaa.gov/erddap",
        "documentation_url": "https://www.ncei.noaa.gov/erddap/",
        "dataset_name": "Satellite Sea Surface Temperature & Global Ocean Wave Heights",
        "access_type": "public",
        "license_notes": "Public domain US Federal geospatial oceanographic service",
        "update_frequency": "6-Hourly",
        "historical_coverage": "2002 - Present",
        "fields": ["sea_surface_temp_c", "significant_wave_height_m", "ocean_current_u", "ocean_current_v"],
        "auth_required": False,
        "active": True,
        "last_success_at": "30 minutes ago",
        "last_error": None,
        "rate_limit_notes": "REST queries with griddap / tabledap protocols",
    },
    {
        "id": "src-worldbank-pink",
        "source_name": "World Bank Commodity Pink Sheet",
        "provider": "The World Bank Group",
        "base_url": "https://www.worldbank.org/en/research/commodity-markets",
        "documentation_url": "https://datacatalog.worldbank.org/search/dataset/0038238/commodity-prices-history-and-projections",
        "dataset_name": "Monthly Global Commodity Prices (Crude Oil, Gas, Fertilizer, Metals)",
        "access_type": "public",
        "license_notes": "Creative Commons Attribution 4.0 International (CC BY 4.0)",
        "update_frequency": "Monthly (First week)",
        "historical_coverage": "1960 - Present",
        "fields": ["crude_oil_brent_usd_bbl", "crude_oil_wti_usd_bbl", "natural_gas_us_usd_mmbtu", "iron_ore_usd_dmt"],
        "auth_required": False,
        "active": True,
        "last_success_at": "12 hours ago",
        "last_error": None,
        "rate_limit_notes": "Public REST & CSV downloadable datasets",
    },
    {
        "id": "src-worldbank-indicators",
        "source_name": "World Bank Indicators API",
        "provider": "The World Bank Group",
        "base_url": "https://api.worldbank.org/v2",
        "documentation_url": "https://datahelpdesk.worldbank.org/knowledgebase/articles/889392",
        "dataset_name": "World Development Indicators (GDP, Industrial Activity, Export Values)",
        "access_type": "public",
        "license_notes": "CC BY 4.0 World Bank Open Data Policy (API access without key)",
        "update_frequency": "Annual / Quarterly",
        "historical_coverage": "1960 - Present",
        "fields": ["gdp_growth_annual_pct", "exports_goods_services_usd", "manufacturing_value_added_usd"],
        "auth_required": False,
        "active": True,
        "last_success_at": "1 day ago",
        "last_error": None,
        "rate_limit_notes": "Direct REST JSON endpoints without mandatory authentication token",
    },
    {
        "id": "src-fred",
        "source_name": "FRED Economic Data",
        "provider": "Federal Reserve Bank of St. Louis",
        "base_url": "https://api.stlouisfed.org/fred",
        "documentation_url": "https://fred.stlouisfed.org/docs/api/fred/",
        "dataset_name": "Global Economic Series: Trade-Weighted US Dollar, CPI, Interest Rates",
        "access_type": "api",
        "license_notes": "Free API access for research and commercial use with registration key",
        "update_frequency": "Daily / Weekly",
        "historical_coverage": "1973 - Present",
        "fields": ["trade_weighted_usd_index", "us_diesel_retail_price", "industrial_production_index"],
        "auth_required": True,
        "active": False,
        "last_success_at": None,
        "last_error": "API Key Required (FRED_API_KEY)",
        "rate_limit_notes": "Rate limit: 120 requests per minute",
    },
    {
        "id": "src-imf",
        "source_name": "IMF Data APIs",
        "provider": "International Monetary Fund",
        "base_url": "https://dataservices.imf.org/REST/SDMX_JSON.svc",
        "documentation_url": "https://data.imf.org/en/Resource-Pages/IMF-API",
        "dataset_name": "Direction of Trade Statistics (DOTS) & World Economic Outlook (WEO)",
        "access_type": "public",
        "license_notes": "Public RESTful data API; terms of use require attribution",
        "update_frequency": "Monthly / Quarterly",
        "historical_coverage": "1980 - Present",
        "fields": ["bilateral_goods_exports_usd", "bilateral_goods_imports_usd", "trade_balance_usd"],
        "auth_required": False,
        "active": True,
        "last_success_at": "8 hours ago",
        "last_error": None,
        "rate_limit_notes": "SDMX-JSON REST API with rate throttling",
    },
    {
        "id": "src-eia",
        "source_name": "U.S. Energy Information Administration (EIA)",
        "provider": "U.S. Department of Energy",
        "base_url": "https://api.eia.gov/v2",
        "documentation_url": "https://www.eia.gov/opendata/documentation.php",
        "dataset_name": "Petroleum & Bunker Fuel Statistics (VLSFO / MGO Benchmarks)",
        "access_type": "api",
        "license_notes": "U.S. Government public domain open energy data with free registered key",
        "update_frequency": "Weekly",
        "historical_coverage": "1990 - Present",
        "fields": ["us_bunker_fuel_price_usd_gal", "rotterdam_marine_gasoil_usd_mt", "crude_stocks_mbbl"],
        "auth_required": True,
        "active": False,
        "last_success_at": None,
        "last_error": "API Key Required (EIA_API_KEY)",
        "rate_limit_notes": "V2 API requires registered x-api-key",
    },
    {
        "id": "src-panama-canal",
        "source_name": "Panama Canal Transit Statistics",
        "provider": "Autoridad del Canal de Panamá (ACP)",
        "base_url": "https://pancanal.com/en/statistics/",
        "documentation_url": "https://pancanal.com/en/statistics/",
        "dataset_name": "Monthly Vessel Transits, Net Tonnage (CP/SUAB) & Draft Restriction Advisories",
        "access_type": "public",
        "license_notes": "Official ACP statistical bulletins and navigation advisories",
        "update_frequency": "Monthly",
        "historical_coverage": "2000 - Present",
        "fields": ["transits_oceangoing_commercial", "neopanamax_transits", "panamax_transits", "transit_tonnage_k_long_tons"],
        "auth_required": False,
        "active": True,
        "last_success_at": "1 day ago",
        "last_error": None,
        "rate_limit_notes": "Standard HTTP retrieval of published monthly reports",
    },
    {
        "id": "src-natural-earth",
        "source_name": "Natural Earth Global Ports",
        "provider": "Natural Earth Data / NACIS",
        "base_url": "https://www.naturalearthdata.com",
        "documentation_url": "https://www.naturalearthdata.com/downloads/10m-cultural-vectors/ports/",
        "dataset_name": "Global Maritime Port Coordinates, Infrastructure & Reference Cartography",
        "access_type": "public",
        "license_notes": "Public Domain (Free for any use including commercial)",
        "update_frequency": "Static Baseline",
        "historical_coverage": "Baseline 2024",
        "fields": ["port_name", "country_code", "latitude", "longitude", "scale_rank", "feature_class"],
        "auth_required": False,
        "active": True,
        "last_success_at": "5 days ago",
        "last_error": None,
        "rate_limit_notes": "Local static vector dataset bundled into system fixtures",
    },
    {
        "id": "src-baltic-exchange",
        "source_name": "Baltic Exchange Freight Indices",
        "provider": "Baltic Exchange Information Services Ltd",
        "base_url": "https://api.balticexchange.com/v1",
        "documentation_url": "https://www.balticexchange.com/en/data-services/market-information0/indices.html",
        "dataset_name": "Dry Bulk (BDI), Tanker (BDTI/BCTI) & Container Benchmark Assessments",
        "access_type": "licensed",
        "license_notes": "LICENSE REQUIRED / NOT AVAILABLE. Commercial proprietary index; requires enterprise subscription license. Never scrape.",
        "update_frequency": "Daily (17:00 UTC)",
        "historical_coverage": "1985 - Present",
        "fields": ["index_value", "route_assessment_usd", "time_charter_average", "daily_change"],
        "auth_required": True,
        "active": False,
        "last_success_at": None,
        "last_error": "LICENSE REQUIRED / NOT AVAILABLE (BALTIC_API_KEY required for production target)",
        "rate_limit_notes": "Subscription API rate limits apply per licensed seat",
    },
    {
        "id": "src-marinetraffic",
        "source_name": "MarineTraffic AIS Telemetry",
        "provider": "MarineTraffic / Kpler",
        "base_url": "https://services.marinetraffic.com/api",
        "documentation_url": "https://servicedocs.marinetraffic.com/tag/AIS-API/",
        "dataset_name": "Real-time & Historical Vessel Tracking and Port Call Events",
        "access_type": "licensed",
        "license_notes": "Commercial API license required; credit-based API subscription. Support: https://support.marinetraffic.com/en/articles/9552659-api-services",
        "update_frequency": "Near Real-Time (5s terrestrial / 15m satellite)",
        "historical_coverage": "2016 - Present",
        "fields": ["imo", "mmsi", "latitude", "longitude", "speed_knots", "heading", "destination", "eta", "status"],
        "auth_required": True,
        "active": False,
        "last_success_at": None,
        "last_error": "License Required (MARINETRAFFIC_API_KEY required)",
        "rate_limit_notes": "Credit-based commercial consumption per API call",
    },
    {
        "id": "src-shanghai-shipping-exchange",
        "source_name": "Shanghai Shipping Exchange (SCFI / CCFI)",
        "provider": "Shanghai Shipping Exchange (SSE)",
        "base_url": "https://en.sse.net.cn",
        "documentation_url": "https://en.sse.net.cn/indices/scfinew.jsp",
        "dataset_name": "Shanghai Containerized Freight Index (SCFI) & China Containerized Freight Index (CCFI)",
        "access_type": "authorized_exchange",
        "license_notes": "Authorized exchange assessment data. Ingestion interface staged for historical import.",
        "update_frequency": "Weekly (Fridays 15:00 CST)",
        "historical_coverage": "2009 - Present",
        "fields": ["observation_date", "route_corridor", "origin", "destination", "freight_index", "freight_rate", "currency", "unit", "container_vessel_type"],
        "auth_required": False,
        "active": False,
        "last_success_at": None,
        "last_error": "Pending Authorized Dataset Ingestion (Target Architecture Ready)",
        "rate_limit_notes": "Batch CSV/JSON ingestion pipeline or authorized SSE feed",
    },
]

@router.get("/data-sources")
def list_data_sources():
    from app.config import settings
    import httpx
    try:
        key = settings.SUPABASE_ANON_KEY or settings.SUPABASE_SERVICE_ROLE_KEY
        if key and "mock" not in settings.SUPABASE_URL:
            with httpx.Client(timeout=3.0) as client:
                res = client.get(
                    f"{settings.SUPABASE_URL.rstrip('/')}/rest/v1/data_sources?select=*",
                    headers={"apikey": key, "Authorization": f"Bearer {key}"}
                )
                if res.status_code == 200:
                    data = res.json()
                    if len(data) > 0:
                        return data
    except Exception:
        pass
    return REGISTRY_SOURCES

@router.get("/data-sources/{id}")
def get_data_source(id: str):
    sources = list_data_sources()
    for src in sources:
        if src["id"] == id:
            return src
    raise HTTPException(status_code=404, detail="Data source not found")

